In [1]:
import rawpy
import imageio
import glob
import os
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import clear_output, display
import PIL as Image
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import sklearn.metrics as metrics

from pathlib import Path
import joblib

In [2]:
def get_slices(rgb,size):
    # DEFINES THE SUBSETS
    height = rgb.shape[0]
    width = rgb.shape[1]

    vertical_slices = []
    horizontal_slices = []

    K = height//size + 1
    for k in range(K):
        t = slice(k*size,min([(k+1)*size,height-1]))
        vertical_slices.append(t)

    N = width//size + 1
    for n in range(N):
        t = slice(n*size,min([(n+1)*size,width-1]))
        horizontal_slices.append(t)
        
    return (vertical_slices,horizontal_slices)

In [3]:
import numpy as np

# Load the file
data = np.load('photos_train.npz')

# List all the arrays stored in the file
print(data.files)

images = data['Image']

['Image', 'Date', 'Species', 'Multiple']


In [4]:
print(images)

[[[[  4   4   2]
   [  5   5   3]
   [  5   5   3]
   ...
   [  3   3   1]
   [  3   3   1]
   [  3   3   1]]

  [[  4   4   2]
   [  4   4   2]
   [  5   5   3]
   ...
   [  3   3   1]
   [  3   3   1]
   [  3   3   1]]

  [[  3   3   1]
   [  4   4   2]
   [  4   4   2]
   ...
   [  3   3   1]
   [  3   3   1]
   [  3   3   1]]

  ...

  [[ 15  15  13]
   [ 14  14  12]
   [ 14  14  12]
   ...
   [ 38  38  36]
   [ 38  39  34]
   [ 37  38  33]]

  [[ 15  15  13]
   [ 14  14  12]
   [ 14  14  12]
   ...
   [ 38  38  36]
   [ 37  38  33]
   [ 37  38  33]]

  [[ 15  15  13]
   [ 14  14  12]
   [ 14  14  12]
   ...
   [ 37  37  35]
   [ 37  38  33]
   [ 36  37  32]]]


 [[[  4   4   2]
   [  4   4   2]
   [  4   4   2]
   ...
   [  3   3   3]
   [  3   3   3]
   [  3   3   3]]

  [[  4   4   2]
   [  4   4   2]
   [  4   4   2]
   ...
   [  3   3   3]
   [  3   3   3]
   [  3   3   3]]

  [[  4   4   2]
   [  4   4   2]
   [  4   4   2]
   ...
   [  3   3   3]
   [  3   3   3]
   [  3   3

In [8]:
print(images[0].shape)
print(type(images))

(2240, 3360, 3)
<class 'numpy.ndarray'>


In [6]:
def Hand_Label(NpArray):
    labels = [None] * len(NpArray)
    i = 0



    while i < len(NpArray):
        plt.axis("off")
        plt.imshow(NpArray[i])
        plt.show()

        user_input = input(f"[{i+1}] Is this empty? (y= yes, n= no, b=back, c=exit): ").lower()
        clear_output()
        plt.clf()
        if (user_input) == 'y' or user_input == 'n':
            labels[i] = 1 if user_input == 'y' else 0
            i += 1
        elif (user_input) == 'b':
            if i > 0:
                i-=1
            else:
                print("You are already at the first image")
        elif user_input == 'c':
            break
        else:
            print("Please give a proper input: (y= yes, n= no, b=back, c=exit): ")
    return labels[:i]
                









    
    

In [7]:
Hand_Label(images)

[1, 0, 1, 1, 1, 1, 1, 1, 0]

<Figure size 640x480 with 0 Axes>